import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";
import { sortSidebarEntries } from "./src/components/sidebar-order.js";

const config: Config = {
  title: "Documentation Numspot",
  tagline: "L'offre de référence de cloud souverain et de confiance",
  favicon: "img/favicon.svg",

  // Set the production url of your site here
  url: "https://docs.numspot.com/",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/",

  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",

  clientModules: [
    "./src/client/sidebar-accordion.ts",
    "./src/client/sticky-doc-title.ts",
  ],

  trailingSlash: true,

  // Makes the OpenAPI spec discoverable by tools/AI from any page.
  // The /openapi page renders the spec client-side (Scalar via JS), so a plain
  // HTML fetch never sees the content. These links point straight at the
  // machine-readable source. `service-desc` is the standard IANA relation for a
  // service description (OpenAPI).
  headTags: [
    {
      tagName: "link",
      attributes: {
        rel: "service-desc",
        type: "application/openapi+json",
        href: "https://api.eu-west-2.numspot.com/openapi",
        title: "Numspot API — spécification OpenAPI (source vivante)",
      },
    },
    {
      tagName: "link",
      attributes: {
        rel: "describedby",
        type: "application/yaml",
        href: "/files/openapi.yaml",
        title: "Numspot API — spécification OpenAPI (miroir statique)",
      },
    },
    {
      tagName: "link",
      attributes: {
        rel: "service-desc",
        type: "application/openapi+json",
        href: "https://objectstorage.eu-west-2.numspot.com/openapi",
        title: "Numspot Object Storage API — spécification OpenAPI",
      },
    },
  ],

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "fr",
    locales: ["fr", "en"],
    path: "i18n",
    localeConfigs: {
      fr: {
        label: "Français",
        direction: "ltr",
        htmlLang: "fr-FR",
        calendar: "gregory",
        path: "fr",
      },
      en: {
        label: "English",
        direction: "ltr",
        // British English (see i18n direction)
        htmlLang: "en-GB",
        calendar: "gregory",
        path: "en",
      },
    },
  },

  presets: [
    [
      "classic",
      {
        sitemap: {
          lastmod: "date",
          //changefreq: 'weekly',
          //priority: 0.5,
          //ignorePatterns: ['/tags/**'],
          filename: "sitemap.xml",
          //createSitemapItems: async (params) => {
          //  const {defaultCreateSitemapItems, ...rest} = params;
          //  const items = await defaultCreateSitemapItems(rest);
          //  return items.filter((item) => !item.url.includes('/page/'));
          //},
        },
        docs: {
          sidebarPath: "./sidebars.ts",
          // Compute each page's last-modified date from git history. Rendered
          // under the page title by src/components/LastUpdatedDate (see the
          // MDXComponents swizzle); the default theme footer is disabled via
          // the DocItem/Footer override.
          showLastUpdateTime: true,
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          // editUrl: 'https://github.com/numspot/docs',
          routeBasePath: "/",
          // "Accueil" (home) and "Premiers pas" (getting-started) are placed
          // explicitly first in the sidebar (sidebars.ts); remove them from
          // the autogenerated slice to avoid duplicates. Everything else is
          // ordered at build time by src/components/sidebar-order.ts
          // (highlighted entries first, then alphabetical, within each
          // visual group).
          async sidebarItemsGenerator({ defaultSidebarItemsGenerator, ...args }) {
            const items = await defaultSidebarItemsGenerator(args);
            const explicitIds = new Set(["docs/home", "docs/getting-started"]);
            const withoutExplicit = items.filter(
              (item) => !(item.type === "doc" && explicitIds.has(item.id)),
            );
            return sortSidebarEntries(withoutExplicit, args.docs);
          },
        },
        blog: false,
        // blog: {
        //   showReadingTime: true,
        //   // Please change this to your repo.
        //   // Remove this to remove the "edit this page" links.
        //   //editUrl: 'https://github.com/numspot/docs',
        // },
        theme: {
          customCss: ["./src/css/custom.css", "./src/css/changelog.css"],
        },
        // Google Analytics (GA4). The plugin injects the gtag.js tag into the
        // <head> of ALL pages and tracks route changes (SPA).
        // Active only in the production build (`docusaurus build`),
        // not in `docusaurus start`.
        gtag: {
          trackingID: "G-QG7XN3BDKR",
          anonymizeIP: true,
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    "./src/plugins/strip-null-bytes.js",
    "docusaurus-plugin-image-zoom",
    // Redirects for renamed slugs (old slugs → new ones), non-indexed.
    // RULE + mapping: see ./src/plugins/slug-redirects.js and CONVENTIONS-SLUGS.md.
    "./src/plugins/slug-redirects.js",
  ],

  themes: [
    "@docusaurus/theme-mermaid",
    // Local search (fully self-hosted, no request to any third party).
    // Replaces docusaurus-lunr-search, which only did exact matching: "snap"
    // did not find "snapshot", and the 3.5 MB index was parsed on the main
    // thread before the input became usable.
    // Here the index is split per locale, fetched and queried inside a web
    // worker, with prefix wildcards (LEADING/TRAILING) and fuzzy matching.
    [
      "@easyops-cn/docusaurus-search-local",
      {
        // The content hash is carried by the FILE NAME: the index becomes
        // immutable and can be cached for a year (see container/nginx.conf).
        hashed: "filename",
        language: ["fr", "en"],
        // Directories whose content feeds the file-name hash. The default
        // ("docs") ignores i18n/: an English-only translation change would not
        // have changed the file name, and the immutable cache would have served
        // a stale English index.
        docsDir: ["docs", "i18n"],
        indexDocs: true,
        indexBlog: false,
        indexPages: true,
        // `routeBasePath: "/"` in the preset (docs-only mode): the index must
        // target the same root, otherwise no doc page is indexed at all.
        docsRouteBasePath: "/",
        highlightSearchTermsOnTargetPage: true,
        searchResultLimits: 10,
        searchResultContextMaxLength: 60,
        // Shows the "Page > Section" path: essential here, since the index
        // goes down to heading level (more than 1700 entries).
        explicitSearchResultPath: true,
        // Edit distance 1: "kubernets" finds "kubernetes".
        fuzzyMatchingDistance: 1,
      },
    ],
  ],
  // In order for Mermaid code blocks in Markdown to work,
  // you also need to enable the Remark plugin with this option
  markdown: {
    mermaid: true,
  },

  themeConfig: {
    zoom: {
      selector: ".markdown :not(a) > img:not(.no-zoom)",
      background: {
        light: "rgba(240, 240, 240, 0.9)",
        dark: "rgb(50, 50, 50, 0.9)",
      },
      config: {},
    },
    docs: {
      sidebar: {
        hideable: true,
      },
    },
    // Replace with your project's social card
    image: "img/numspot-social-card.png",
    navbar: {
      logo: {
        alt: "Numspot",
        src: "img/numspot_wordmark.svg",
        srcDark: "img/numspot_wordmark_white.svg",
      },
      items: [
        {
          type: "doc",
          docId: "docs/home",
          position: "right",
          label: "Docs",
        },
        {
          href: "https://numspot.com/produits-et-disponibilites/",
          label: "Produits",
          position: "right",
        },
        {
          type: "localeDropdown",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Numspot",
          items: [
            {
              label: "numspot.com",
              href: "https://numspot.com/",
            },
            {
              label: "Carrières",
              href: "https://numspot.com/carrieres/",
            },
          ],
        },
        {
          title: "Réseaux sociaux",
          items: [
            {
              label: "Linkedin",
              href: "https://www.linkedin.com/company/numspot/",
            },
          ],
        },
        {
          title: "Outils",
          items: [
            {
              label: "GitHub",
              href: "https://github.com/numspot",
            },
            {
              label: "Console Numspot",
              href: "https://auth.eu-west-2.numspot.com/",
            },
          ],
        },
        {
          title: "Support",
          items: [
            {
              label: "Contactez-nous",
              href: "mailto:support-client@numspot.com",
            },
            {
              label: "Signaler un incident de sécurité",
              href: "https://numspot.com/signalement-de-vulnerabilites-et-incidents-de-securite/",
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Numspot SAS.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
