import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    // Home first, before everything else, outside the "Ressources & outils"
    // (Resources & Tools) group.
    { type: "doc", id: "docs/home" },
    // Getting started right after Accueil, before the OpenAPI category:
    // explicit item, outside the autogenerated slice (see the
    // sidebarItemsGenerator filter in docusaurus.config.ts).
    { type: "doc", id: "docs/getting-started" },
    // OpenAPI category first (outside the docs tree): the spec is rendered by
    // standalone pages (/openapi/, /openapi-object-storage/). Links aligned with
    // the OpenAPI navbar menu. The "Ressources & outils" group label and the
    // icon are set in CSS via the "openapi" class.
    {
      type: "category",
      label: "OpenAPI",
      className: "section-title openapi",
      collapsed: true,
      items: [
        { type: "link", label: "Global", href: "/openapi/" },
        { type: "link", label: "Object Storage", href: "/openapi-object-storage/" },
        { type: "link", label: "Data Loss Prevention", href: "/openapi-dlp/" },
      ],
    },
    {
      type: "autogenerated",
      dirName: "docs",
    },
  ],
};

export default sidebars;
