/**
 * Sidebar ordering — build time, consumed by the `sidebarItemsGenerator`
 * override in docusaurus.config.ts. Plain CommonJS on purpose: the linter
 * test suite (node --test, zero dependency) requires this module to unit-test
 * the ordering — see linter/tests/sidebar-order.test.js.
 *
 * Menu entries are sorted with highlighted entries first, then alphabetical
 * (Intl.Collator pinned to "fr" for deterministic builds). Two levels only:
 *  - level 0: top-level entries (Compute, Network…) — sorted WITHIN their
 *    visual group, so the group labels ("Ressources & outils", "Nos
 *    services", "Management & gouvernance") keep separating contiguous
 *    blocks. Accueil and OpenAPI are explicit sidebars.ts items, outside
 *    this module's scope (Accueil stays first; OpenAPI stays pinned as the
 *    first tool).
 *  - level 1: direct children of each top-level entry. Deeper levels keep
 *    their `sidebar_position` ordering.
 *
 * Group labels are injected in CSS (::before) on the FIRST item of each
 * group. That item depends on the sort result, so the sort marks it with a
 * `group-head-*` class (see GROUP_HEAD_CLASS) that the CSS keys on.
 */

// Entries rendered above their alphabetical siblings.
// Keys are locale-stable paths below the docs root:
//  - level 0: "<folder>"          e.g. "compute"
//  - level 1: "<folder>/<child>"  e.g. "compute/vms"
//
// Current highlights (user decision, 2026-09-23):
//  - level 0: Terraform, Services Managés (OpenAPI is pinned first by
//    sidebars.ts — highlighting it would be a no-op, so no key);
//  - level 1: every top-level "Concepts" entry, Kubernetes (under Services
//    Managés) and VM (under Compute).
// "Global" (first child of the OpenAPI menu) is ordered manually in
// sidebars.ts, outside the autogenerated slice.
const HIGHLIGHTED_SIDEBAR_ENTRIES = new Set([
  // level 0
  'terraform',
  'managed-services',
  // level 1 — top-level "Concepts" entries
  'compute/concept',
  'catalog/concepts',
  'inventory/concepts',
  'managed-services/concepts',
  // level 1 — services
  'managed-services/kubernetes',
  'compute/vms',
]);

// Visual groups, in render order. Each group stays a contiguous block and
// its entries are sorted within the group. The first group's head is pinned:
// OpenAPI (explicit sidebars.ts item, first in the DOM) carries the
// "Ressources & outils" label, so group 0 needs no marker.
const SIDEBAR_GROUPS = [
  ['terraform', 'glossary', 'support', 'faq', 'changelog'],
  ['managed-services', 'compute', 'network', 'storage', 'connectivity'],
  ['iam', 'catalog', 'inventory'],
];

// CSS marker class appended to the sorted-first item of each group whose
// label must follow the sort result (group 0 is pinned to OpenAPI).
const GROUP_HEAD_CLASS = [undefined, 'group-head-services', 'group-head-governance'];

/**
 * Minimal structural view of a sidebar item. The default generator strips
 * `source`/`position` from its output (only `type`, `label`, `id`, `items`,
 * `className`, `key`, `link`, `customProps`… survive), so identity is derived
 * from the docs themselves — see keyOf().
 *
 * @typedef {object} SidebarSortItem
 * @property {string} type
 * @property {string} [label]
 * @property {string} [id]
 * @property {string} [className]
 * @property {{ type: string, id?: string }} [link]
 * @property {SidebarSortItem[]} [items]
 */

/**
 * Slice of the docs metadata the generator receives (args.docs).
 *
 * @typedef {object} SidebarSortDoc
 * @property {string} id
 * @property {string} sourceDirName
 */

/**
 * @typedef {{
 *   docsById: Map<string, SidebarSortDoc>,
 *   depth: number,
 *   parentKey?: string,
 *   highlighted: ReadonlySet<string>,
 * }} Ctx
 */

// Pinned locale: localeCompare without an explicit locale falls back to the
// runtime default, which varies between machines and would make the build
// nondeterministic. "fr" also sorts EN labels correctly for ASCII input.
const collator = new Intl.Collator('fr', { sensitivity: 'base', numeric: true });

/**
 * Locale-stable identity of an entry:
 *  - doc  → last id segment ("changelog" from "docs/changelog");
 *  - category → the docs-root-relative folder its descendants share
 *    ("terraform" from docs/terraform/**, "vms" from docs/compute/vms/**).
 * A category whose ONLY child is its index doc (e.g. resources/ where
 * resources.mdx matches the folder name, glossary/ with index.mdx) is left
 * childless by the generator (the child becomes the category link): fall
 * back to the folder of that linked doc.
 *
 * @param {SidebarSortItem} item
 * @param {Ctx} ctx
 * @returns {string}
 */
function keyOf(item, ctx) {
  if (item.type !== 'category') {
    const segment = item.id ? item.id.split('/').pop() : undefined;
    return segment ?? '';
  }
  return firstDescendantFolder(item, ctx) ?? linkedDocFolder(item, ctx) ?? '';
}

/**
 * Folder segment shared by the category's descendant docs at its depth. The
 * depth stays FIXED while descending: every descendant of a category lives
 * under the same folder at that depth (docs/<folder>/… for level 0).
 *
 * @param {SidebarSortItem} item
 * @param {Ctx} ctx
 * @returns {string | undefined}
 */
function firstDescendantFolder(item, ctx) {
  for (const child of item.items ?? []) {
    if (child.type === 'category') {
      const nested = firstDescendantFolder(child, ctx);
      if (nested) return nested;
    } else if (child.id) {
      const dir = ctx.docsById.get(child.id)?.sourceDirName;
      const segment = dir ? dir.split('/')[ctx.depth] : undefined;
      if (segment) return segment;
    }
  }
  return undefined;
}

// Folder of the doc a childless category links to, derived from that doc's
// sourceDirName at the category's depth (glossary: link id
// "docs/glossary/index" → sourceDirName "docs/glossary" → "glossary").
//
// @param {SidebarSortItem} item
// @param {Ctx} ctx
// @returns {string | undefined}
function linkedDocFolder(item, ctx) {
  if (item.link && item.link.type === 'doc' && item.link.id) {
    const dir = ctx.docsById.get(item.link.id)?.sourceDirName;
    const segment = dir ? dir.split('/')[ctx.depth] : undefined;
    if (segment) return segment;
  }
  return undefined;
}

/**
 * @param {SidebarSortItem} item
 * @param {Ctx} ctx
 * @returns {string}
 */
function labelOf(item, ctx) {
  if (typeof item.label === 'string' && item.label) return item.label;
  return keyOf(item, ctx);
}

/**
 * Full key of an entry, prefixed by its parent key at level 1
 * ("compute/vms"). Level 0 keys have no prefix ("compute").
 *
 * @param {SidebarSortItem} item
 * @param {Ctx} ctx
 * @returns {string}
 */
function entryKey(item, ctx) {
  const key = keyOf(item, ctx);
  return ctx.parentKey ? `${ctx.parentKey}/${key}` : key;
}

/**
 * @param {SidebarSortItem} item
 * @param {Ctx} ctx
 * @returns {boolean}
 */
function isHighlighted(item, ctx) {
  return ctx.highlighted.has(entryKey(item, ctx));
}

/**
 * @param {SidebarSortItem} a
 * @param {SidebarSortItem} b
 * @param {Ctx} ctx
 * @returns {number}
 */
function compareEntries(a, b, ctx) {
  const highlightDelta =
    (isHighlighted(a, ctx) ? 0 : 1) - (isHighlighted(b, ctx) ? 0 : 1);
  if (highlightDelta !== 0) return highlightDelta;
  return collator.compare(labelOf(a, ctx), labelOf(b, ctx));
}

/**
 * Sort a top-level slice: level 0 within each visual group (groups stay
 * contiguous, unknown entries keep their relative order at the end), then
 * level 1 within each top-level entry. Mutates and returns `items`.
 *
 * @template {SidebarSortItem} T
 * @param {T[]} items top-level sidebar slice (already home-filtered)
 * @param {readonly SidebarSortDoc[]} docs docs metadata from the generator args
 * @param {ReadonlySet<string>} [highlighted] injectable for tests
 * @returns {T[]}
 */
function sortSidebarEntries(items, docs, highlighted = HIGHLIGHTED_SIDEBAR_ENTRIES) {
  const docsById = new Map(docs.map((doc) => [doc.id, doc]));
  const rootCtx = { docsById, depth: 1, highlighted };

  const buckets = SIDEBAR_GROUPS.map(() => []);
  const ungrouped = [];
  for (const item of items) {
    const groupIndex = SIDEBAR_GROUPS.findIndex((group) =>
      group.includes(keyOf(item, rootCtx)),
    );
    if (groupIndex === -1) ungrouped.push(item);
    else buckets[groupIndex].push(item);
  }

  const sortedGroups = buckets.map((bucket, groupIndex) => {
    const sorted = [...bucket].sort((a, b) => compareEntries(a, b, rootCtx));
    const headClass = GROUP_HEAD_CLASS[groupIndex];
    const head = sorted[0];
    if (headClass && head) {
      head.className = [head.className, headClass].filter(Boolean).join(' ');
    }
    return sorted;
  });
  const level0 = [...sortedGroups.flat(), ...ungrouped];

  for (const item of level0) {
    if (item.type === 'category' && Array.isArray(item.items)) {
      const childCtx = {
        docsById,
        depth: 2,
        parentKey: keyOf(item, rootCtx),
        highlighted,
      };
      item.items = [...item.items].sort((a, b) => compareEntries(a, b, childCtx));
    }
  }

  return level0;
}

module.exports = {
  HIGHLIGHTED_SIDEBAR_ENTRIES,
  SIDEBAR_GROUPS,
  GROUP_HEAD_CLASS,
  sortSidebarEntries,
};
